site_name: Javaland 2024 GPT Clone in Kotlin

# Meta tags (placed in header)
site_description: GPT Clone in Kotlin
site_author: Michal Harakal, Alexander von Below, Falk Sippach
site_url: https://github.com/michalharakal/KPTChat

# Repository (add link to repository on each page)
repo_name: Javaland 2024 Workshop
repo_url: https://github.com/michalharakal/KPTChat
edit_uri: blob/javaland-2024/javaland2024/mkdocs/src/doc/docs/

# Copyright (shown at the footer)
copyright: 'Copyright &copy; 2024 Michal Harakal, Alexander von Below, Falk Sippach'

# Material theme
theme:
  name: 'material'
  favicon: favicon.svg
  social:
    - type: 'github'
      link: 'https://github.com/michalharakal/KPTChat'
  features:
    - navigation.expand
    - navigation.tabs
    - navigation.instant
    - navigation.indexes
    - navigation.top

# Extensions
markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: false
  - footnotes
  - meta
  - def_list
  - toc:
      permalink: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.smartsymbols
  - admonition
  - attr_list
  - md_in_html
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format

          # Dev server binding for livereload
dev_addr: 127.0.0.1:3001

nav:
  - Home:
      - index.md
      - "Who we are" : bios.md
      - "Setup" : setup.md

extra_css:
  - kmp_colors.css
