name: Publish to GitHub Pages
on:
  push:
    branches: [develop]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
concurrency:
  group: github-pages
  cancel-in-progress: false
# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: write
  pages: write
  id-token: write
jobs:
  publish:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Configure Pages
        uses: actions/configure-pages@v3
      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
      - name: Install Antora
        run: |
          npm i antora
          npm i asciidoctor-kroki && \
          npm i asciidoctor-plantuml && \
          npm i asciidoctor-external-callout && \
          npm i @asciidoctor/tabs && \
          npm i @antora/collector-extension && \
          npm i yaml && \
          npm i @antora/lunr-extension
      - name: Generate Site
        run: |
          cd docs
          npx antora antora-playbook.yml
      - name: Upload Artifacts
        uses: actions/upload-pages-artifact@v2
        with:
          path: docs/_public
      - name: Deploy docs to website
        uses: JamesIves/github-pages-deploy-action@releases/v4
        with:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            BRANCH: site
            FOLDER: ./docs/_public
            TARGET_FOLDER: docs/
            CLEAN: true